// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffjqsccmzafmzsdtearh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmanFzY2NtemFmbXpzZHRlYXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTMzODUsImV4cCI6MjA4ODIyOTM4NX0.UwKn5axTEdzrqM5QS5AmxW75h1WIFeJxwV9eVsNUMvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});